use std::fs;
use std::path::Path;

fn main() {
    let articles_dir = Path::new("content/articles");
    println!("cargo:rerun-if-changed=content/articles");

    let mut entries: Vec<(String, String)> = Vec::new();

    if articles_dir.exists() {
        for entry in fs::read_dir(articles_dir).expect("read content/articles") {
            let path = entry.expect("dir entry").path();
            if path.extension().and_then(|s| s.to_str()) == Some("md") {
                let slug = path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .expect("md stem")
                    .to_string();
                let abs = path
                    .canonicalize()
                    .expect("canonicalize article")
                    .to_string_lossy()
                    .to_string();
                println!("cargo:rerun-if-changed={}", abs);
                entries.push((slug, abs));
            }
        }
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs — do not edit\n");
    out.push_str("pub const ARTICLES: &[(&str, &str)] = &[\n");
    for (slug, abs) in &entries {
        out.push_str(&format!(
            "    (\"{}\", include_str!(r\"{}\")),\n",
            slug, abs
        ));
    }
    out.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(format!("{}/articles_manifest.rs", out_dir), out).expect("write manifest");
}
