use std::fs;
use std::path::Path;

/// Walk `content/articles/` and emit a manifest of `(slug, lang, &str)`
/// entries. English lives at the top level (`content/articles/<slug>.md`);
/// translations live one level deeper (`content/articles/<lang>/<slug>.md`).
fn main() {
    let articles_dir = Path::new("content/articles");
    println!("cargo:rerun-if-changed=content/articles");

    // (slug, lang, absolute_path)
    let mut entries: Vec<(String, String, String)> = Vec::new();

    if articles_dir.exists() {
        // English (top-level *.md files).
        for entry in fs::read_dir(articles_dir).expect("read content/articles") {
            let path = entry.expect("dir entry").path();
            if path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("md") {
                let slug = path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .expect("md stem")
                    .to_string();
                let abs = path
                    .canonicalize()
                    .expect("canonicalize article")
                    .to_string_lossy()
                    .to_string();
                println!("cargo:rerun-if-changed={}", abs);
                entries.push((slug, "en".to_string(), abs));
            }
        }

        // Translated subdirectories (e.g. content/articles/es/, content/articles/zh-CN/).
        for entry in fs::read_dir(articles_dir).expect("read content/articles") {
            let path = entry.expect("dir entry").path();
            if !path.is_dir() {
                continue;
            }
            let lang = match path.file_name().and_then(|s| s.to_str()) {
                Some(s) => s.to_string(),
                None => continue,
            };
            if lang.starts_with('.') || lang.starts_with('_') {
                continue;
            }
            println!("cargo:rerun-if-changed={}", path.display());
            for sub in fs::read_dir(&path).expect("read lang dir") {
                let sub_path = sub.expect("lang entry").path();
                if sub_path.is_file()
                    && sub_path.extension().and_then(|s| s.to_str()) == Some("md")
                {
                    let slug = sub_path
                        .file_stem()
                        .and_then(|s| s.to_str())
                        .expect("md stem")
                        .to_string();
                    let abs = sub_path
                        .canonicalize()
                        .expect("canonicalize translated article")
                        .to_string_lossy()
                        .to_string();
                    println!("cargo:rerun-if-changed={}", abs);
                    entries.push((slug, lang.clone(), abs));
                }
            }
        }
    }

    // Sort by (lang, slug) for a deterministic manifest.
    entries.sort_by(|a, b| a.1.cmp(&b.1).then(a.0.cmp(&b.0)));

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs — do not edit\n");
    out.push_str("pub const ARTICLES: &[(&str, &str, &str)] = &[\n");
    for (slug, lang, abs) in &entries {
        out.push_str(&format!(
            "    (\"{}\", \"{}\", include_str!(r\"{}\")),\n",
            slug, lang, abs
        ));
    }
    out.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(format!("{}/articles_manifest.rs", out_dir), out).expect("write manifest");
}
